name: Deploy to Vercel and NPM

on:
  push:
    branches: [main]

# on:
#   workflow_run:
#     workflows: ["Tests"]
#     branches: [main]
#     types: 
#       - completed

jobs:
  chromatic-storybook:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}